#pragma once

#ifndef CONFIG_KVA_WIFI_SSID
#define CONFIG_KVA_WIFI_SSID "The Chateau"
#endif

#ifndef CONFIG_KVA_WIFI_PASSWORD
#define CONFIG_KVA_WIFI_PASSWORD "thechateau"
#endif

#ifndef CONFIG_KVA_SAMPLE_RATE
#define CONFIG_KVA_SAMPLE_RATE 16000
#endif

#ifndef CONFIG_KVA_CAPTURE_MS
#define CONFIG_KVA_CAPTURE_MS 2500
#endif

#ifndef CONFIG_KVA_WAKE_WORD_SENSITIVITY
#define CONFIG_KVA_WAKE_WORD_SENSITIVITY 60
#endif

#ifndef CONFIG_KVA_SIMULATED_WAKE_INTERVAL_MS
#define CONFIG_KVA_SIMULATED_WAKE_INTERVAL_MS 0
#endif

#ifndef CONFIG_KVA_TTS_VOICE
#define CONFIG_KVA_TTS_VOICE "alloy"
#endif

#ifndef CONFIG_KVA_SPOTIFY_DEVICE_NAME
#define CONFIG_KVA_SPOTIFY_DEVICE_NAME "Korvo-1"
#endif

#ifndef CONFIG_KVA_SPOTIFY_VOLUME_STEP
#define CONFIG_KVA_SPOTIFY_VOLUME_STEP 10
#endif

#ifndef CONFIG_KVA_AWS_TELEMETRY_PERIOD_MS
#define CONFIG_KVA_AWS_TELEMETRY_PERIOD_MS 15000
#endif

#ifndef CONFIG_KVA_LED_STRIP_GPIO
#define CONFIG_KVA_LED_STRIP_GPIO 19
#endif

#ifndef CONFIG_KVA_LED_COUNT
#define CONFIG_KVA_LED_COUNT 12
#endif

#ifndef CONFIG_KVA_LED_BRIGHTNESS
#define CONFIG_KVA_LED_BRIGHTNESS 32
#endif

#ifndef CONFIG_KVA_BUTTON1_GPIO
#define CONFIG_KVA_BUTTON1_GPIO -1
#endif

#ifndef CONFIG_KVA_BUTTON1_ACTIVE_LOW
#define CONFIG_KVA_BUTTON1_ACTIVE_LOW 1
#endif

#ifndef CONFIG_KVA_BUTTON_DEBOUNCE_MS
#define CONFIG_KVA_BUTTON_DEBOUNCE_MS 120
#endif

#ifndef CONFIG_KVA_CODEC_I2C_SDA
#define CONFIG_KVA_CODEC_I2C_SDA -1
#endif

#ifndef CONFIG_KVA_CODEC_I2C_SCL
#define CONFIG_KVA_CODEC_I2C_SCL -1
#endif

#ifndef CONFIG_KVA_CODEC_I2S_BCLK
#define CONFIG_KVA_CODEC_I2S_BCLK -1
#endif

#ifndef CONFIG_KVA_CODEC_I2S_LRCLK
#define CONFIG_KVA_CODEC_I2S_LRCLK -1
#endif

#ifndef CONFIG_KVA_CODEC_I2S_DATA
#define CONFIG_KVA_CODEC_I2S_DATA -1
#endif

#ifndef CONFIG_KVA_CODEC_I2S_MCLK
#define CONFIG_KVA_CODEC_I2S_MCLK -1
#endif

#ifndef CONFIG_KVA_CODEC_I2S_PORT
#define CONFIG_KVA_CODEC_I2S_PORT 1
#endif

#ifndef CONFIG_KVA_SPOTIFY_USE_CSPOT
#define CONFIG_KVA_SPOTIFY_USE_CSPOT 0
#endif
